package iot.ttu.edu.M2MRuleEditor.ui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class RuleListItemDesign extends VerticalLayout {
	protected ComboBox logicComboBox;
	protected Label textLabel;
	protected ComboBox sensorComboBox;
	protected ComboBox sensorResourceComboBox;
	protected ComboBox operatorComboBox;
	protected TextField valueTextField;
	protected Button addButtun;
	protected Button removeButton;

	public RuleListItemDesign() {
		Design.read(this);
	}
}
